# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_votes_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='author',
        ),
    ]
